server:
  port: 8014
spring:
  datasource:
    url:  jdbc:mysql://10.70.21.75:3306/test?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: hello1234!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: eking.micro.javaframework.wallet
  aop:
    auto: true

mybatis:
  mapperLocations: classpath:mybatis/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.70.21.78:8761/eureka/,http://10.70.21.79:8761/eureka/
